# Generated by Django 5.1.7 on 2025-03-24 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bird',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=256)),
                ('genus', models.CharField(blank=True, max_length=128, null=True)),
                ('species', models.CharField(blank=True, max_length=128, null=True)),
                ('link', models.CharField(blank=True, max_length=512, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('bird', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='merlin.bird')),
            ],
            options={
                'indexes': [models.Index(fields=['date'], name='merlin_dete_date_9c2f82_idx')],
            },
        ),
    ]
