# Generated by Django 5.1.7 on 2025-03-24 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merlin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='merlin_loca_name_7e278d_idx')],
            },
        ),
        migrations.AddField(
            model_name='detection',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='merlin.location'),
            preserve_default=False,
        ),
    ]
