# Generated by Django 5.1.7 on 2025-03-25 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merlin', '0005_alter_bird_family_alter_family_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='bird',
            name='slug',
            field=models.SlugField(blank=True, max_length=256, null=True),
        ),
    ]
