# Generated by Django 5.1.7 on 2025-03-25 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merlin', '0006_bird_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bird',
            name='common_name',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='bird',
            name='slug',
            field=models.SlugField(max_length=256),
        ),
    ]
