# Generated by Django 5.1.7 on 2025-03-28 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merlin', '0008_alter_family_name_alter_location_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bird',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='static/merlin/images/'),
        ),
    ]
