# Generated by Django 5.1.7 on 2025-03-29 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merlin', '0009_bird_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bird',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='merlin/static/images/'),
        ),
    ]
